---

- hosts: all
# strategy: free
  tasks:
    - include_role:
        name: domain
      when: "'dc' in group_names"
    - include_role:
        name: wazuh_stack
      when: "'wazuh_stack' in group_names"

- hosts: windows
  tasks:
    - include_role:
        name: common
      when: "'win10' in group_names"

# Domain-join clients and run post-domain configuration in parallel
- hosts: windows
# strategy: free
  tasks:
    - include_role: 
        name: win10
      when: "'win10' in group_names"
    - include_role:
        name: dc
      when: "'dc' in group_names"


# Run the agent on the Windows Hosts
- hosts: windows
  roles:
    - wazuh_agent